// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DragController from "./drag_controller"
application.register("drag", DragController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PdfEditorController from "./pdf_editor_controller"
application.register("pdf-editor", PdfEditorController)

import ResizeController from "./resize_controller"
application.register("resize", ResizeController)

import SignaturePreviewController from "./signature_preview_controller"
application.register("signature-preview", SignaturePreviewController)
